### PR TITLE
feat(sdk): add timestamp flag

### PR DESCRIPTION
**Pull request by m1ga**
Add a `--timestamp` or `ti config cli.timestamp true` flag to the CLI. It will display a timestamp (already implemented) before the log output:
```
2022-04-07T09:13:04.546Z - [INFO]  
```

### CODE REVIEW

**Review by caspahouzer — COMMENTED** [review]
With the already included timestamps the logs getting longer and longer

```
2022-04-07T10:19:02.479Z - [TRACE] User defaults from command line:
2022-04-07T10:19:02.479Z - [TRACE]     IDEDerivedDataPathOverride = /Users/sebastianklaus/Documents/Apps/fantastic-library/build/iphone/DerivedData
2022-04-07T10:19:02.479Z - [TRACE]     IDEPackageSupportUseBuiltinSCM = YES
2022-04-07T10:19:02.479Z - [TRACE]     UseNewBuildSystem = YES
2022-04-07T10:19:02.479Z - [TRACE] Build settings from command line:
2022-04-07T10:19:02.479Z - [TRACE]     OBJROOT = /Users/sebastianklaus/Documents/Apps/fantastic-library/build/iphone/build/Intermediates
2022-04-07T10:19:02.479Z - [TRACE]     ONLY_ACTIVE_ARCH = 1
2022-04-07T10:19:02.479Z - [TRACE]     SHARED_PRECOMPS_DIR = /Users/sebastianklaus/Documents/Apps/fantastic-library/build/iphone/build/Intermediates/PrecompiledHeaders
2022-04-07T10:19:02.479Z - [TRACE]     SYMROOT = /Users/sebastianklaus/Documents/Apps/fantastic-library/build/iphone/build/Products
2022-04-07T10:19:03.217Z - [TRACE] note: Using new build system
2022-04-07T10:19:03.224Z - [TRACE] note: Planning
2022-04-07T10:19:03.286Z - [TRACE] Analyze workspace
```

Should we show just the time instead of complete date? Or even make it configurable?

**Comment by m1ga** [comment]
Think we can do that afterwards. Since there was only one person asking for it I've made the flag public :smile: I personally don't see a use-case for this unless you have some testing running somewhere and want to check at what time/day the log occurred. And then it's very useful to have date + time. And you can convert that into a date object easily and write a custom ui for logs.

default is still off so I don't think many people will have an issue with the length

**Comment by caspahouzer** [comment]
What should we do with this PR?

**Comment by m1ga** [comment]
Its just adding a minor new feature, nothing critical for the first release. So up to you guy to implement it or wait for it. Nothing high demanding.

**Pull request merged**
